toolbar:
  - undo redo | bold italic underline strikethrough | styleselect | alignleft aligncenter alignright alignjustify
  - fontselect fontsizeselect | image | link
  - uploadimage
plugins:
  - image
  - link
  - uploadimage

relative_urls : false
remove_script_host : false
convert_urls : false